Repository WorldOfDarknessXIII/World-of-Darkness-13, pull requests merged in 2024-12, with the labels that each got.

#350 [Need Review] National Guard Antagonist (Admin Button)
  code/__DEFINES/role_preferences.dm
  code/__HELPERS/names.dm
  code/game/gamemodes/objective.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/one_click_antag.dm
  code/modules/mob/living/living_defines.dm
  code/modules/projectiles/ammunition/_firing.dm
  code/modules/vtmb/frenzy.dm
  code/modules/vtmb/gamemodes/masquerade.dm
  code/modules/vtmb/ghoul_species.dm
  code/modules/vtmb/jobs/national_guard.dm
  code/modules/wod13/clothcode.dm
  code/modules/wod13/npc_movement.dm
  code/modules/wod13/procs.dm
  tgstation.dme
Labels: enhancement

#393 PD Changes for themaskedreader (BOUNTY???)
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/modules/vtmb/jobs/fbi.dm
  code/modules/vtmb/jobs/police.dm
Labels: bounty

#395 Adds police vendor to the PD
  code/modules/mining/machine_vending.dm
  code/modules/wod13/food.dm
Labels: bounty, Feature, Quality of Life

#399 Thaumaturgy Fixes and Changes
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/modules/vtmb/magic/mysticism.dm
  code/modules/vtmb/magic/pyramid.dm
  code/modules/wod13/melee.dm
  tgstation.dme
Labels: Fix, Balance, Feature, Refactor

#391 SWAT NPCs can handcuff and leave after you're down
  code/modules/mob/living/simple_animal/hostile/retaliate/spaceman.dm
  code/modules/wod13/mobs.dmi
Labels: enhancement, Fix, Feature

#370 Adds The Cross And Bible For Purchase
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/modules/wod13/food.dm
Labels: Feature

#401 [HOTFIX] Important contact not existing if someone rolled that role from roundstart
  code/modules/vtmb/electronics/phones/phone.dm
Labels: Fix

#392 Fix the chance that being embraced by a violating appearance clan to spawn you in the nosferatu town
  code/modules/vtmb/vampire_clane/clane.dm
Labels: Fix

#416 Makes bloodhunt name the author
  code/modules/vtmb/gamemodes/bloodhunt.dm
  code/modules/wod13/special_shit.dm
Labels: Quality of Life

#407 Replaces the Tremere badges
  code/modules/vtmb/jobs/jobs.dm
  code/modules/vtmb/jobs/regent.dm
  code/modules/wod13/items.dmi
  code/modules/wod13/worn.dmi
  code/modules/wod13/worn_fat.dmi
  code/modules/wod13/worn_slim_f.dmi
  code/modules/wod13/worn_slim_m.dmi
Labels: Feature

#394 Tiny changes
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/projectiles/projectile.dm
  code/modules/surgery/organs/vocal_cords.dm
  code/modules/vtmb/archetypes.dm
  code/modules/vtmb/disciplines.dm
  code/modules/vtmb/ghoul_species.dm
  code/modules/vtmb/kindred_species.dm
  code/modules/wod13/car.dm
  code/modules/wod13/doorcode.dm
  code/modules/wod13/lombard.dm
Labels: Feature, Quality of Life
