Repository WorldOfDarknessXIII/World-of-Darkness-13, pull requests merged in 2025-03, with the labels that each got.

#918 Make molotovs explode a random amount of time after being lit
  code/modules/wod13/guns.dm
Labels: Fix

#896 Pedantically change cholesterine to cholesterol
  code/modules/wod13/food.dm
Labels: Tweak

#906 Removes transformation diseases from the game
  code/datums/diseases/transformation.dm
  code/datums/diseases/wizarditis.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/monkey/monkey.dm
  code/modules/antagonists/monkey/monkey.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/reagent_containers/bottle.dm
  code/modules/research/xenobiology/xenobiology.dm
  tgstation.dme
Labels: Removal

#875 Fixes a Visible Matrix in NosTown and the Clinic Garage Door Access
  _maps/map_files/Vampire/SanFrancisco.dmm
Labels: Map Edit

#905 FBI vest
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/modules/vtmb/jobs/fbi.dm
  code/modules/vtmb/jobs/police.dm
  code/modules/wod13/clothcode.dm
  code/modules/wod13/clothing.dmi
  code/modules/wod13/worn.dmi
  code/modules/wod13/worn_fat.dmi
  code/modules/wod13/worn_slim_f.dmi
  code/modules/wod13/worn_slim_m.dmi
Labels: Feature, Fix, Map Edit

#888 Let Salubri with Iron Gullet feed on corpses
  code/datums/keybinding/human.dm
Labels: Vampire

#913 Sorts stores & clothes into subfolders.
  code/modules/wod13/clothcode.dm
  code/modules/wod13/food.dm
  code/modules/wod13/items/clothes/belt.dm
  code/modules/wod13/items/clothes/eyes.dm
  code/modules/wod13/items/clothes/feet.dm
  code/modules/wod13/items/clothes/hands.dm
  code/modules/wod13/items/clothes/head.dm
  code/modules/wod13/items/clothes/mask.dm
  code/modules/wod13/items/clothes/neck.dm
  code/modules/wod13/items/clothes/suit.dm
  code/modules/wod13/items/clothes/under.dm
  code/modules/wod13/items/stores/clothes.dm
  code/modules/wod13/items/stores/food.dm
  code/modules/wod13/items/stores/guns.dm
  code/modules/wod13/items/stores/misc.dm
  tgstation.dme
Labels: Code Improvement, Quality of Life

#848 Infinite Order bug fix 2
  code/modules/cargo/expressconsole.dm
Labels: Fix

#612 Reduces drug lab cost by 60%
  code/modules/wod13/cargo.dm
Labels: Balance, Tweak, Requires Testing Evidence

#882 Female Cops
  code/modules/wod13/npcroles.dm
Labels: Feature

#625 Properly removes Diablerist quirk
  code/modules/wod13/quirks.dm
Labels: Fix, Vampire, Requires Testing Evidence

#803 Fixes plantgrowth_tests.dm
  code/modules/unit_tests/plantgrowth_tests.dm
Labels: Fix

#856 Adds mixer and rag to da club
  _maps/map_files/Vampire/SanFrancisco.dmm
Labels: Map Edit

#893 Makes the cost of raising your Dharma level scale with level (also, a non-critical but substantial bug fix)
  code/modules/client/preferences.dm
  code/modules/vtmb/dharma.dm
Labels: Balance, Fix, Kuei-jin

#900 Changes the amount of ghouls that can be playing the Police Officer role simultaneously from one to two.
  code/modules/vtmb/jobs/police.dm
Labels: Balance

#901 Fixes cocaine adulteration and adds a recipe for morphine adulteration from reagent bottles.
  code/modules/wod13/packadulteration.dm
Labels: Fix, Tweak

#911 Salubri 4 anarkz
  code/modules/vtmb/jobs/anarchs/bouncer.dm
  code/modules/vtmb/jobs/anarchs/emissary.dm
  code/modules/vtmb/jobs/anarchs/sweeper.dm
Labels: Quality of Life, Vampire

#752 Squidqueen Bounty - Nosferatu Hair and Ear, Gargoyle Hair changes
  code/modules/vtmb/vampire_clane/gargoyle.dm
  code/modules/vtmb/vampire_clane/nosferatu.dm
  icons/mob/human_parts_greyscale.dmi
Labels: Feature, Quality of Life, Bounty

#944 Buff Disciplines
  code/__DEFINES/wod13/discipline.dm
  code/modules/wod13/datums/powers/discipline/__discipline_power.dm
  code/modules/wod13/datums/powers/discipline/auspex.dm
  code/modules/wod13/datums/powers/discipline/bloodheal.dm
  code/modules/wod13/datums/powers/discipline/celerity.dm
  code/modules/wod13/datums/powers/discipline/fortitude.dm
  code/modules/wod13/datums/powers/discipline/obfuscate.dm
  code/modules/wod13/datums/powers/discipline/potence.dm
Labels: Balance, Vampire, Tweak

#608 Adds click-dragging items to a pawnshop/black market to sell every item of that exact type
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/__DEFINES/_helpers.dm
  code/game/objects/items.dm
  code/modules/surgery/organs/ears.dm
  code/modules/surgery/organs/eyes.dm
  code/modules/surgery/organs/heart.dm
  code/modules/surgery/organs/liver.dm
  code/modules/surgery/organs/lungs.dm
  code/modules/surgery/organs/stomach.dm
  code/modules/surgery/organs/tongue.dm
  code/modules/wod13/clock.dm
  code/modules/wod13/datums/selling.dm
  code/modules/wod13/fishing.dm
  code/modules/wod13/guns.dm
  code/modules/wod13/items/clothes/feet.dm
  code/modules/wod13/items/clothes/head.dm
  code/modules/wod13/items/clothes/suit.dm
  code/modules/wod13/items/clothes/under.dm
  code/modules/wod13/items/narcotics/meth/cocaine.dm
  code/modules/wod13/items/narcotics/meth/meth.dm
  code/modules/wod13/items/narcotics/weed/weed.dm
  code/modules/wod13/items/narcotics/weed/weedpack.dm
  code/modules/wod13/lombard.dm
  code/modules/wod13/melee.dm
  tgstation.dme
Labels: Tweak
