Repository WorldOfDarknessXIII/World-of-Darkness-13, pull requests merged in 2025-01, with the labels that each got.

#384 Increase the number of max save slots.
  code/modules/client/preferences.dm
Labels: Feature, Quality of Life

#398 Add a choice to keep being a vampire after a embrace or after being turned into a ghoul
  code/modules/vtmb/kindred_species.dm
Labels: Feature

#385 Fix Ambitious bugs, new objective, removed drinking blood from the pool.
  code/game/gamemodes/objective.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/vtmb/jobs/jobs.dm
Labels: Fix

#521 backpack no longer lags your game
  code/modules/vtmb/gridventory.dm
Labels: good first issue, Fix

#509 Car rebalancing & QOL pt. 1
  code/modules/wod13/car.dm
Labels: Balance

#517 Turns vampire_faction strings into FACTION_[faction] defines
  code/__DEFINES/factions.dm
  code/game/objects/structures/guillotine.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/ghost.dm
  code/modules/vtmb/faction_war.dm
  code/modules/vtmb/ghoul_species.dm
  code/modules/vtmb/jobs/anarchs/baron.dm
  code/modules/vtmb/jobs/anarchs/bouncer.dm
  code/modules/vtmb/jobs/anarchs/emissary.dm
  code/modules/vtmb/jobs/anarchs/sweeper.dm
  code/modules/vtmb/jobs/archivist.dm
  code/modules/vtmb/jobs/dealer.dm
  code/modules/vtmb/jobs/giovanni.dm
  code/modules/vtmb/jobs/jobs.dm
  code/modules/vtmb/jobs/prince.dm
  code/modules/vtmb/jobs/regent.dm
  code/modules/vtmb/jobs/sabbat.dm
  code/modules/vtmb/jobs/scourge.dm
  code/modules/vtmb/jobs/seneschal.dm
  code/modules/vtmb/jobs/sheriff.dm
  code/modules/vtmb/jobs/supply_assistant.dm
  code/modules/vtmb/kindred_species.dm
  code/modules/vtmb/vampire_clane/nosferatu.dm
  code/modules/wod13/ambient.dm
  code/modules/wod13/npcroles.dm
  tgstation.dme
Labels: code improvement

#507 Injury slowdown will now scale with the user's max health
  code/modules/mob/living/carbon/human/human.dm
Labels: Balance

#531 Fix Toreador access to Torea-Doors
  code/modules/wod13/doorcode.dm
Labels: Fix

#516 Readjusts values & lessens the amount of corpsed bodies
  code/modules/surgery/organs/ears.dm
  code/modules/surgery/organs/eyes.dm
  code/modules/surgery/organs/heart.dm
  code/modules/surgery/organs/liver.dm
  code/modules/surgery/organs/lungs.dm
  code/modules/surgery/organs/stomach.dm
  code/modules/surgery/organs/tongue.dm
  code/modules/wod13/food.dm
  code/modules/wod13/narco.dm
Labels: Balance

#523 Bites with bloody lover now looks like a kiss
  code/datums/keybinding/human.dm
  code/modules/wod13/onyxcombat.dm
Labels: enhancement

#437 Reduces Blood Heal's burn damage healing by 75%.
  code/modules/vtmb/ghoul_species.dm
Labels: Balance, Refactor, code improvement

#548 Changes the manifest Groupings
  code/datums/datacore.dm
Labels: Quality of Life

#511 Clinic update
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/__DEFINES/jobs.dm
  code/__DEFINES/preferences.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/jobs/jobs.dm
  code/modules/vtmb/jobs/doctor.dm
  code/modules/vtmb/jobs/jobs.dm
  code/modules/wod13/clothcode.dm
  code/modules/wod13/clothing.dmi
  code/modules/wod13/doorcode.dm
  code/modules/wod13/onfloor.dmi
  code/modules/wod13/worn.dmi
  code/modules/wod13/worn_fat.dmi
  code/modules/wod13/worn_slim_f.dmi
  code/modules/wod13/worn_slim_m.dmi
Labels: Feature, Map Edit, Sprites

#570 Fix Torpor bug
  code/modules/mob/living/carbon/carbon.dm
Labels: Fix, Vampire

#524 Ports better IV drip sprites
  icons/obj/iv_drip.dmi
Labels: Needs pictures, Sprites

#446 Chinatown expansion!
  _maps/map_files/Vampire/SanFrancisco.dmm
Labels: Map Edit

#574 Expands what splats dealer can be
  code/controllers/subsystem/job.dm
  code/modules/vtmb/jobs/dealer.dm
Labels: Vampire, Werewolf, Kuei-jin

#567 Disable Atmos, Part 1
  code/__DEFINES/subsystems.dm
  code/controllers/subsystem/adjacent_air.dm
  code/controllers/subsystem/air.dm
  code/modules/atmospherics/environmental/LINDA_turf_tile.dm
Labels: Performance, Test Merge Candidate

#532 Car rebelancing & QOL pt. 2
  code/modules/mob/living/carbon/werewolf/lupus.dm
  code/modules/mob/living/carbon/werewolf/werewolf.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/vtmb/jobs/taxi.dm
  code/modules/vtmb/vampire_clane/tzimisce.dm
  code/modules/wod13/car.dm
  code/modules/wod13/npc.dm
Labels: Balance, Fix, Quality of Life

#461 Potence nerf and an unarmed combat change
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/monkeys.dm
  code/modules/mob/living/carbon/human/species_types/mushpeople.dm
  code/modules/mob/living/carbon/human/species_types/synths.dm
  code/modules/wod13/mannequin.dm
Labels: Balance, Fix, Vampire

#409 Vampires now take extra damage from being on fire.
  code/modules/vtmb/kindred_species.dm
Labels: Balance, Vampire

#601 implements job bans?
  code/modules/admin/sql_ban_system.dm
Labels: Test Merge Candidate

#598 Port json_savefile from /tg/ to turn character sheets and prefs into json for some sanity
  code/datums/json_savefile.dm
  tgstation.dme
Labels: Test Merge Candidate, Tools, Port

#510 Make Dice Rolls Pretty
  code/__DEFINES/preferences.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_toggles.dm
  code/modules/vtmb/disciplines.dm
  code/modules/vtmb/kindred_species.dm
  code/modules/wod13/narco.dm
  code/modules/wod13/procs.dm
  code/modules/wod13/verbs/dice.dm
  tgstation.dme
Labels: Code Improvement, Feature
