Repository WorldOfDarknessXIII/World-of-Darkness-13, pull requests merged in 2025-02, with the labels that each got.

#549 Fixes say without breaking hotkey say, fixes coloring on input bar
  code/__DEFINES/colors.dm
  code/modules/client/client_procs.dm
  code/modules/mob/living/carbon/carbon_say.dm
  code/modules/mob/mob_say.dm
Labels: Code Improvement, Fix

#682 Speech bubble overlay no longer gets stuck on
  code/modules/mob/living/carbon/carbon_say.dm
Labels: Fix

#442 Nerfs diablerie
  code/modules/wod13/bloodsucking.dm
Labels: Balance, Vampire

#477 Click-dragging simple-mobs such as mice should now properly allow aggressive grabs
  code/_onclick/click.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Quality of Life

#678 Prince Office / Panic Room / Tower Upper Level Remap + Creates Primogen Access
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/modules/vtmb/jobs/regent.dm
  code/modules/wod13/ambient.dm
  code/modules/wod13/doorcode.dm
  code/modules/wod13/tiles.dmi
Labels: Map Edit

#703 Seneschal Armory / Panic Room Pincode Fix
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/modules/vtmb/electronics/keypads/keypad.dm
  code/modules/vtmb/kindred_species.dm
Labels: Map Edit

#721 Fixes the Police Chief's door being invisible
  _maps/map_files/Vampire/SanFrancisco.dmm
  _maps/map_files/Vampire/runtimetown.dmm
  code/modules/wod13/doorcode.dm
Labels: Map Edit

#720 Adds Pentex Clothing
  code/modules/wod13/clothcode.dm
  code/modules/wod13/clothing.dmi
  code/modules/wod13/onfloor.dmi
  code/modules/wod13/worn.dmi
  code/modules/wod13/worn_fat.dmi
  code/modules/wod13/worn_slim_f.dmi
  code/modules/wod13/worn_slim_m.dmi
Labels: Sprites, Bounty

#731 Fixes BSD Totem Portal Marker
  _maps/map_files/Mining/Lavaland.dmm
Labels: Fix, Map Edit, Oversight, Werewolf

#717 Fixes Accidental Deletion of Old Clan Stairs/TransferPoint from Pentex Remap
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/modules/vtmb/electronics/p25.dm
  code/modules/wod13/ambient.dm
  code/modules/wod13/flavledders.dm
  code/modules/wod13/tiles.dmi
Labels: Fix, Map Edit, Review Again

#661 hunting rifle and semi-auto handgun
  code/modules/vtmb/gridventory.dm
  code/modules/vtmb/jobs/national_guard.dm
  code/modules/vtmb/jobs/primogen.dm
  code/modules/vtmb/jobs/triad.dm
  code/modules/wod13/48x32weapons.dmi
  code/modules/wod13/ammo.dmi
  code/modules/wod13/cargo.dm
  code/modules/wod13/food.dm
  code/modules/wod13/guns.dm
  code/modules/wod13/lefthand.dmi
  code/modules/wod13/onfloor.dmi
  code/modules/wod13/righthand.dmi
  code/modules/wod13/weapons.dmi
Labels: Balance, Quality of Life, Sprites

#736 Someone missed an / here!!
  code/modules/wod13/ambient.dm
Labels: Fix, Good First PR

#695 Ventrue Domain Remap
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/game/objects/structures/watercloset.dm
Labels: Feature, Map Edit

#688 Prevent stuns on vampire bite
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/wod13/signals_kindred.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/werewolf/transformation.dm
  code/modules/vtmb/kindred_species.dm
  code/modules/vtmb/kuei_jin.dm
  code/modules/vtmb/werewolf_species.dm
  code/modules/wod13/bloodsucking.dm
  tgstation.dme
Labels: Balance, Frozen, Vampire, Werewolf

#739 make payphones actually show
  code/modules/vtmb/electronics/phones/phone.dm
Labels: Fix, Oversight

#743 Garou Gift Fixes [COPY OF PR BY NYVREM]
  code/modules/vtmb/werewolf/gifts.dm
  code/modules/vtmb/werewolf/tribes.dm
Labels: freeze exempt

#610 Weed tray and drug lab tweaks
  code/modules/wod13/narco.dm
Labels: Fix

#643 Recycler no longer deletes itself
  code/game/machinery/recycler.dm
Labels: Fix

#677 reroll the roll code
  code/modules/client/preferences.dm
  code/modules/client/preferences_toggles.dm
  code/modules/wod13/verbs/dice.dm
Labels: Code Improvement, Fix

#709 Dispatcher radio follow up
  code/modules/projectiles/ammunition/_firing.dm
  code/modules/vtmb/electronics/phones/phone.dm
  code/modules/wod13/npc.dm
  code/modules/wod13/onyxcombat.dm
  code/modules/wod13/witness.dm
Labels: Fix, Oversight, Quality of Life

#716 De-Racisms a lot of the NPCs 2
  code/modules/wod13/npcroles.dm
Labels: Fix, Oversight

#740 Removes blushing from Charmer
  code/modules/mob/living/carbon/human/examine.dm
Labels: Quality of Life, Removal

#733 Gives Everyone 3 Quirk Points
  code/modules/client/preferences.dm
Labels: Quality of Life, Werewolf

#738 Silver bullet nerf
  code/__DEFINES/wod13/status_effects.dm
  code/__DEFINES/wod13/status_effects_debuffs.dm
  code/modules/wod13/ammostack.dm
  code/modules/wod13/status_effects/debuffs.dm
  tgstation.dme
Labels: Balance, Code Improvement, Feature

#649 Adds Limousine Sprites+Obj Code
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/modules/wod13/car.dm
  code/modules/wod13/cars.dmi
Labels: Map Edit, Sprites, Bounty

#722 update hallucinations
  code/modules/flufftext/Hallucination.dm
Labels: Feature, Quality of Life, Vampire

#719 Bear - The Return of the Bearening
  code/modules/wod13/bear.dm
  tgstation.dme
Labels: Feature

#773 Fixes mapmerge git hooks and tools (includes #711 since that's what I was using to test and I approved it)
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/__DEFINES/wod13/dcs/bouncer_signals.dm
  code/__DEFINES/wod13/dcs/gun_signals.dm
  code/__DEFINES/wod13/subsystems.dm
  code/__DEFINES/wod13/traits.dm
  code/modules/projectiles/guns/wod13/ballistic.dm
  code/modules/projectiles/wod13/gun.dm
  code/modules/vtmb/jobs/stripper.dm
  code/modules/wod13/areas/interior/strip_elysium.dm
  code/modules/wod13/datums/bouncer_roles/bouncer_elysium_role.dm
  code/modules/wod13/datums/bouncer_roles/bouncer_giovanni_role.dm
  code/modules/wod13/datums/bouncer_roles/bouncer_mob_role.dm
  code/modules/wod13/datums/vip_barrier_perm.dm
  code/modules/wod13/effects/elysium_barrier.dm
  code/modules/wod13/effects/elysium_stripclub_barrier.dm
  code/modules/wod13/effects/giovanni_barrier.dm
  code/modules/wod13/effects/vip_barrier.dm
  code/modules/wod13/npc.dm
  code/modules/wod13/npc_aggression.dm
  code/modules/wod13/npc_movement.dm
  code/modules/wod13/npcroles.dm
  code/modules/wod13/npcs/bouncer_elysium.dm
  code/modules/wod13/npcs/bouncer_giovanni.dm
  code/modules/wod13/npcs/bouncer_mob.dm
  code/modules/wod13/subsystems/ssBouncerBarrier.dm
  dependencies.sh
  icons/obj/wod13/barrier.dmi
  sound/wod13/bouncer_blocked.ogg
  tgstation.dme
  tools/bootstrap/python36._pth
  tools/bootstrap/python_.ps1
  tools/hooks/dmi.merge
  tools/hooks/dmm.merge
  tools/hooks/install.sh
  tools/hooks/pre-commit.hook
  tools/hooks/python.sh
  tools/mapmerge2/__init__.py
  tools/mapmerge2/convert.py
  tools/mapmerge2/dmm.py
  tools/mapmerge2/fixup.py
  tools/mapmerge2/merge_driver.py
  tools/requirements.txt
Labels: Feature, Map Edit, Quality of Life, Tools

#652 Techshop keys
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/modules/wod13/doorcode.dm
Labels: Map Edit, Quality of Life

#730 Hand sickle
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/modules/vtmb/gridventory.dm
  code/modules/wod13/lefthand.dmi
  code/modules/wod13/melee.dm
  code/modules/wod13/onfloor.dmi
  code/modules/wod13/righthand.dmi
  code/modules/wod13/weapons.dmi
  code/modules/wod13/worn.dmi
  code/modules/wod13/worn_fat.dmi
  code/modules/wod13/worn_slim_f.dmi
  code/modules/wod13/worn_slim_m.dmi
Labels: Map Edit, Sprites, Bounty

#770 Corrected a single spelling mistake in the character setup menu.
  code/modules/client/preferences.dm
Labels: Fix, Good First PR, Oversight

#252 Automatic TGS DMAPI Update
  code/__DEFINES/tgs.dm
  code/modules/tgs/v5/undefs.dm
Labels: Tools

#754 Allows Malkavians to speak in VTM:B style fonts
  code/modules/mob/living/living_say.dm
  code/modules/vtmb/vampire_clane/malkavian.dm
  icons/hud/actions.dmi
Labels: Feature, Quality of Life, Vampire

#748 Hair Dye
  code/__HELPERS/global_lists.dm
  code/_globalvars/lists/flavor_misc.dm
  code/game/objects/items/dyekit.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/wod13/food.dm
  code/modules/wod13/onfloor.dmi
  icons/mob/hair_gradients.dmi
  icons/obj/dyespray.dmi
  tgstation.dme
Labels: Feature

#788 Fixes the sheriff not having access to seneschal doors
  code/modules/wod13/doorcode.dm
Labels: Fix

#786 Fixes vests not holding anything in the suit storage
  code/modules/wod13/clothcode.dm
Labels: Fix

#791 Removes automatic growl on garou rage gain
  code/game/objects/items/dyekit.dm
  code/modules/jobs/job_exp.dm
  code/modules/vtmb/werewolf_species.dm
  code/modules/wod13/emote.dm
  code/modules/wod13/melee.dm
  tgstation.dme
Labels: Quality of Life, Werewolf

#785 Fixes hallucination fire stacks lingering
  code/modules/flufftext/Hallucination.dm
Labels: Fix

#787 Fixes a typo in the police department sign
  code/modules/wod13/decor.dm
Labels: Fix

#809 NPC AI fixes (NPC's drop weapons less, are 50% less psychotic)
  code/modules/wod13/npc.dm
  code/modules/wod13/npc_aggression.dm
  code/modules/wod13/npc_movement.dm
  code/modules/wod13/npcroles.dm
Labels: Balance, Code Improvement, Refactor

#761 Suitdate
  code/modules/wod13/food.dm
Labels: Quality of Life

#818 Infinite Order bug fix
  code/modules/cargo/expressconsole.dm
Labels: Fix, In Game Exploit

#767 organizing all door code
  code/__DEFINES/wod13/lockpick_difficulty.dm
  code/modules/wod13/doorcode.dm
  code/modules/wod13/items/keys/keys.dm
  code/modules/wod13/items/keys/keys_lockpick.dm
  code/modules/wod13/items/keys/keys_npc.dm
  code/modules/wod13/structures/doors/vampdoor.dm
  code/modules/wod13/structures/doors/vampdoor_glass.dm
  code/modules/wod13/structures/doors/vampdoor_misc.dm
  code/modules/wod13/structures/doors/vampdoor_npc.dm
  code/modules/wod13/structures/doors/vampdoor_police.dm
  code/modules/wod13/structures/doors/vampdoor_wood.dm
  code/modules/wod13/structures/doors/vampdoor_wood_old.dm
  tgstation.dme
Labels: Code Improvement, Refactor

#811 Minor Tower Touch-Ups
  _maps/map_files/Vampire/SanFrancisco.dmm
Labels: Map Edit, Quality of Life

#855 Troll-proof lockpicking
  code/modules/wod13/structures/doors/vampdoor.dm
Labels: Fix

#824 ancillae can be primogen
  code/modules/vtmb/jobs/primogen.dm
  code/modules/vtmb/jobs/regent.dm
  code/modules/vtmb/jobs/voivode.dm
Labels: Quality of Life, Vampire

#852 Chantry, Elysium remaps
  _maps/map_files/Mining/Lavaland.dmm
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/game/machinery/wod13/washing_machine.dm
  code/game/objects/structures/wod13/bedsheet_bin.dm
  code/modules/library/wod13/random_books.dm
  code/modules/wod13/ambient.dm
  code/modules/wod13/food.dm
  code/modules/wod13/items/keys/keys.dm
  code/modules/wod13/structures/doors/vampdoor_glass.dm
  code/modules/wod13/structures/doors/vampdoor_misc.dm
  code/modules/wod13/structures/doors/vampdoor_wood.dm
  code/modules/wod13/structures/doors/vampdoor_wood_old.dm
  code/modules/wod13/wallcode.dm
  icons/mob/inhands/misc/bedsheet_lefthand.dmi
  icons/mob/inhands/misc/bedsheet_righthand.dmi
  icons/obj/bedsheets.dmi
  tgstation.dme
  tools/UpdatePaths/852_remap_chantry.txt
Labels: Map Edit

#861 Converts all save files to json at round end
  code/controllers/configuration/entries/game_options.dm
  code/controllers/configuration/entries/resources.dm
  code/controllers/subsystem/ticker.dm
  code/game/world.dm
  config/config.txt
Labels: Code Improvement

#877 Makes Berlin by Night non-canon again
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/wod13/clothcode.dm
  code/modules/wod13/clothing.dmi
  code/modules/wod13/worn.dmi
  code/modules/wod13/worn_fat.dmi
  code/modules/wod13/worn_slim_f.dmi
  code/modules/wod13/worn_slim_m.dmi
Labels: Removal
